# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neigborhood',
            name='neigborhood_count',
        ),
        migrations.AddField(
            model_name='neigborhood',
            name='occupants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='neigborhood',
            name='neigborhood_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='neigborhood',
            name='neigborhood_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
