# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20180209_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neigborhood',
            new_name='Neighborhood',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='neigborhood_location',
            new_name='neighborhood_location',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='neigborhood_name',
            new_name='neighborhood_name',
        ),
    ]
