# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(null=True),
        ),
    ]
